updated the necessary docs for ethers
PrimeDAO/contracts-v2 pull request #41
Opened 2021-07-06 22:18 UTC by codebuster22

2021-07-06 22:24 UTC, dkent600 submitted a review, later dismissed

2021-07-07 08:29 UTC, kinspotting requested changes
needs minor changes

2021-07-07 08:29 UTC, kinspotting commented on scripts/gnosis.js
> +    // console.log(transactions);
pls delete the comment

2021-07-07 08:29 UTC, kinspotting commented on docs/dapp-integration.md
> +// I hope it returns an object
pls change the comment to "should return an object"

2021-07-07 09:37 UTC, kinspotting requested changes

2021-07-07 09:37 UTC, kinspotting commented on scripts/gnosis.js
> +    // console.log(res.data);
pls delete the comment

2021-07-07 09:37 UTC, kinspotting commented on scripts/change_owner.js
> +const {'rinkeby': {SeedFactory: SEED_FACTORY, Safe}} = require('../contractAddresses.json');
let's not hardcode the network name in the script, network name could be stored in the `.env` file, pls reference to the `contracts` repo

2021-07-07 10:52 UTC, kinspotting approved these changes
lgtm

2021-07-07 10:55 UTC, merged