Refactor scripts
PrimeDAO/contracts-v2 pull request #45
Opened 2021-07-10 09:54 UTC by codebuster22

2021-07-20 14:41 UTC, kinspotting requested changes
Documentation doesn't represent the changes in scripts

2021-07-20 14:41 UTC, kinspotting commented on docs/contract-deployment.md
> +## Deploy Contract
`Deploy Contracts`

2021-07-20 14:41 UTC, kinspotting commented on docs/contract-deployment.md
> +```bash
Deploy on rinkeby:

2021-07-20 14:41 UTC, kinspotting commented on docs/contract-deployment.md
> +
Deploy on mainnet:
```
npm run deploy:contracts:mainnet
```

2021-07-20 14:41 UTC, kinspotting commented on docs/contract-deployment.md
> +## Change Ownership
pls also add mainnet

2021-07-26 11:14 UTC, fabianschu commented
@kinspotting Just as a side note: the README is updated in https://github.com/PrimeDAO/contracts-v2/pull/56, where we change the deployment logic more generally.

2021-07-26 11:50 UTC, kinspotting requested changes

2021-07-26 11:50 UTC, kinspotting commented on package.json
> +    "add:delegate:mainnet": "npx hardhat run scripts/add_delegate.js --network mainnet",
there is no such script in the `scripts` folder

2021-07-26 11:50 UTC, kinspotting commented on package.json
> +    "send:safeTrx:mainnet": "npx hardhat run scripts/add_tx_to_safe.js --network mainnet",
same

2021-07-26 11:50 UTC, kinspotting commented on package.json
>      "deploy:contracts:rinkeby": "npx hardhat run scripts/deploy_contracts.js --network rinkeby",
same

2021-07-26 11:50 UTC, kinspotting commented on package.json
>      "add:delegate:rinkeby": "npx hardhat run scripts/add_delegate.js --network rinkeby",
pls adjust `npm`commands accordingly, also the scripts in `mainnet` and `rinkeby` folders are named in camel case and in the `scripts` folder the `_` is used, pls choose one

2021-07-26 11:50 UTC, kinspotting commented on docs/contract-deployment.md
> +npm run change:factoryOwner:mainnet
not a clear command imho

2021-07-26 11:50 UTC, kinspotting commented on docs/contract-deployment.md
> +npm run add:delegate:mainnet
same here

2021-07-28 12:06 UTC, kinspotting approved these changes

2021-07-28 12:07 UTC, merged